### ISSUE TITLE
Question about the SETUP

### ISSUE THREAD

**Issue by AliBaheri** [GokulNC/Setting-Up-CARLA-RL#1]
Hi @GokulNC,

I have installed CARLA on my machine (Ubuntu 18) and also forked this repo and installed the dependencies. But I am not able to run:

`from Environment.carla_environment_wrapper import CarlaEnvironmentWrapper as CarlaEnv`

Would you please provide some details about how it works and it should be connected to CARLA?

King regards,

**Comment by GokulNC** [comment]
Hi,

Did you check the README file?
That doesn't help? Or what specific doubt do you have? :)

The environment interface that I've setup is somewhat similar to that of Gym.
I'd recommend you take a look at Gym Env first :)

**Comment by AliBaheri** [comment]
Thanks, I was able to resolve the issue.

**Comment by kk2491** [comment]
@AliBaheri Could you please let me know how you fixed the issue. I am having the same issue. 

Thank you,
KK

**Comment by AliBaheri** [comment]
@kk2491 
Check this out:
https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/tree/master/ch7
