### ISSUE TITLE
human_play.py - Angle of view is changing as well

### ISSUE THREAD

**Issue by Tar12** [GokulNC/Setting-Up-CARLA-RL#5]
Both with 0.8.2 and 0.8.4, 

human_play.py 

works fine at navigating the car, but it also oddly rotates the view window (i.e., pressing 'up' key also changes view to looking from up). Is there an easy way to disable this?
Saving screenshots works OK though - it is always from the fixed frontal perspective, this is a visualization issue,

Thanks!

**Comment by GokulNC** [comment]
Ensure that the focus is on terminal while playing the simulator using human_play.py
That is, as soon as the Carla window launches, click on your terminal and start playing. If the focus is on the Carla renderer, it considers `up` arrow key as decreasing the camera field view's Y coordinate I guess.

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 19, 2019 at 7:50 PM, Tar12<notifications@github.com> wrote:   
Both with 0.8.2 and 0.8.4,

human_play.py

works fine at navigating the car, but it also oddly rotates the view window (i.e., pressing 'up' key also changes view to looking from up). Is there an easy way to disable this?
Saving screenshots works OK though - it is always from the fixed frontal perspective, this is a visualization issue,

Thanks!

**Comment by Tar12** [comment]
Thank you! Awesome code!
