### ISSUE TITLE
 Great repository

### ISSUE THREAD

**Issue by DongChen06** [GokulNC/Setting-Up-CARLA-RL#7]
It's really a great repository! Are there any blogs or projects based on this repository, especially on Deep RL? That would be easy for us to learn Carla and RL.  Thank you very much!

**Comment by GokulNC** [comment]
Someone indicated a similar resource to read about Carla and RL here:
https://github.com/GokulNC/Setting-Up-CARLA-Reinforcement-Learning/issues/1#issuecomment-456792115
That may interest you though I haven't personally looked into it.
