### ISSUE TITLE
no CarlaUE4.sh

### ISSUE THREAD

**Issue by nuomizai** [GokulNC/Setting-Up-CARLA-RL#9]
Hi, when I use this rl environment in my project, an error occurs:
[Errno 2] No such file or directory: '/home/didi/CarlaUE4/Binaries/Linux/CarlaUE4.sh'
Because this is the path to the carla binary file CarlaUE4. 
I follow the quick download instructions from calar website, and don't find any shell file in it.
So, do I need to compile the shell file using Unreal Engine? Is there any possible that using this environment without compiling?

**Comment by GokulNC** [comment]
Hey, I used this with Carla release version `0.8.0` only. So I'm not sure about the latest ones.
Really sorry.

**Comment by GokulNC** [comment]
You can maybe check this for similar Carla RL repos:
https://github.com/Amin-Tgz/awesome-CARLA#RL

**Comment by nuomizai** [comment]
> You can maybe check this for similar Carla RL repos:
> https://github.com/Amin-Tgz/awesome-CARLA#RL

Hey, I really want to thank you for your help! I use the version of 0.8.2 from [Carla Repo](https://github.com/carla-simulator/carla/blob/master/Docs/download.md). I've solved this problem by replacing the 'CalarUE4.sh' with 'CarlaUE4' in carla_environment_wrapper.py in the 217 line:

`			cmd = [path.join(environ.get('CARLA_ROOT'), 'CarlaUE4'), self.map,
								  "-benchmark", "-carla-server", "-fps=10", "-world-port={}".format(self.port),
								  "-windowed -ResX={} -ResY={}".format(carla_config.server_width, carla_config.server_height),
								  "-carla-no-hud"]`
`
And I add the CARLA_ROOT in the ~/.bashrc file as:

export CARLA_ROOT=~/CarlaUE4/Binaries/Linux/

Now this environment works well! Thank you again for contributing this excellent reinforcement learning wrapper of Carla! Hope my solution can help others using v 0.8.2

**Comment by nuomizai** [comment]
Another question, is there any possible to close the rendering window of Carla? It makes the training or testing process toooo slow!

**Comment by GokulNC** [comment]
> _Hope my solution can help others using v 0.8.2_

Great, thanks for letting me know. I'll update this on the README.

> _is there any possible to close the rendering window of Carla?_

You can check and see if this works for you on Carla 0.8.3:
https://github.com/carla-simulator/carla/issues/286#issuecomment-393885263
